# Generated by Django 4.1 on 2022-08-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='number1',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='number2',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
