# Generated by Django 4.1 on 2022-08-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactmodel_number1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='number1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='number2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
