# Generated by Django 3.2.13 on 2022-08-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contactmodel_number1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
