# Generated by Django 3.2.13 on 2022-09-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contactmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=25, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='number1',
            field=models.CharField(max_length=25, verbose_name='شماره تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='number2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='شماره '),
        ),
    ]
