# Generated by Django 3.2.13 on 2022-09-01 12:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0006_auto_20220901_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='number2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name=' شماره دوم'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 9, 1, 12, 47, 18, 651793, tzinfo=utc), verbose_name='تاریخ ایجاد شدن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
