# Generated by Django 3.2.13 on 2022-09-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contactmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True, verbose_name='ایمیل'),
        ),
    ]
